### ISSUE TITLE
Sometimes chests result in a logspam/console spam and unable to do anything until force closing the game

### ISSUE THREAD

**Issue by AaronAyante** [AzumattDev/OdinsQOL#28] opened 2022-12-26 03:52 UTC
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
OdinQOL.Patches.AutoStorePatch.DisallowItem (Container container, ItemDrop+ItemData item) (at <74803bbf05b04d9bbed55a7ec73b9e16>:0)
OdinQOL.Patches.AutoStorePatch.TryStoreItem (Container __instance, ItemDrop+ItemData& item) (at <74803bbf05b04d9bbed55a7ec73b9e16>:0)
OdinQOL.Patches.AutoStorePatch+Container_CheckForChanges_Patch.Postfix (Container __instance, ZNetView ___m_nview) (at <74803bbf05b04d9bbed55a7ec73b9e16>:0)
(wrapper dynamic-method) Container.DMD<Container::CheckForChanges>(Container)
MultiUserChest.Patches.InventoryGuiPatch.InventoryGuiUpdatePatch (InventoryGui __instance) (at <c1c2835977164751bf3856a33b26f869>:0)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::Update>(InventoryGui)

![image](https://user-images.githubusercontent.com/50406271/209497653-dedddb52-8f99-478d-a4f5-2e8a5b7bb58e.png)

**Comment by AzumattDev** [comment] 2022-12-26 04:57
It's MultiUserChest.

**Comment by AaronAyante** [comment] 2022-12-26 19:29
> It's MultiUserChest.

Ah, dang. Is there a replacement you know of that should be compatible?

**Comment by AzumattDev** [comment] 2022-12-26 19:29
I do not. I just know the issue is caused by some compatibility problems with Jewelcrafting and other mods what touch inventory with MUC.

**Comment by AaronAyante** [comment] 2022-12-26 19:31
Dang, ah well. Glad to have a cause! I'll nuke MUC and go from there. Thanks mate!

**Comment by MSchmoecker** [comment] 2022-12-26 20:12
It's rather unlikely that this is caused by MUC, in a similar issue #13 (that is now deleted?) this could replicated without MUC. The error itself is throwed in OdinsQOL, while MUC calls the vanilla check for inventory changes on a chest.

Also this code part only reloads the chest inventory more frequently if it is the current open one https://github.com/MSchmoecker/No-Chest-Block/blob/master/MultiUserChest/Patches/InventoryGuiPatch.cs#L13, in vanilla this is normal called delayed by one second but also periodically.

Maybe a timing issue makes it more prominent with MUC but I rather think the root cause is in OdinsQOL.

**Comment by AzumattDev** [comment] 2022-12-26 20:24
Well MUC caused issues in OdinsQOL, Jewelcrafting, and others where it didn't exist before. If by more prominent you mean *much* more likely to happen. Then you'd be right.

There haven't really been any issues like this until now. The DisallowItem issue has been around for awhile and is only when opening world chests. It never fully broke the inventory like it does now. MUC removal will greatly reduce this happening to the point of not existing.

**Comment by MSchmoecker** [comment] 2022-12-26 20:46
But well this is the point. The DisallowItem error is the last one in the stack trace and only invoked by MUC. What I can do is to move the reload elsewhere or wrap it in a try-catch block to prevent further issues down the line. But this will only fix the symptoms, at best it will prevent the inventory from not being usable but the error will be thrown non the less.

And please don't get me wrong, if the error is caused by MUC I will not hesitate to fix it. But from what I see, I could only damage control the resulting error, not fix the root cause.

**Comment by AzumattDev** [comment] 2022-12-26 20:49
All I am mentioning is that the Disallow issue hasn't broken inventories before. Though, I am less concerned with fixing this issue in OdinsQOL as it's already fixed in the standalone mod replacement.

**Closed as completed by AzumattDev** 2022-12-26 20:49 UTC
